name: lint-test-build-deploy

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run:  pip install poetry

      - name: Install Dependencies
        run: poetry install

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          push: false
          tags: ghcr.io/ismael-su/ismael-internship-bot-client:dev

      - name: Test Image
        run: pytest tests/

      - name: Push
        run: docker push ghcr.io/ismael-su/ismael-internship-bot-client:dev